title: Hello, world! I'm Tim Parker.
description: > # this means to ignore newlines until "baseurl:"
  A description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://timparker.me/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tim Parker # add your name
author-img: tim-parker.png # add your photo
about-author: I'm me. # add description
social-github: tparkerd # add your Github handle
social-linkedin: timparkerd # add your Linkedin handle
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
